/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.lxm.pwhelp.utils;

import android.util.Log;

public class LogUtil {
    private static final String DEBUG_TAG = "pwhelper";
    private static final boolean DEBUG_TRACE = true;
    
    public static void i(String tag,String msg) {
    	if(DEBUG_TRACE)	
    		Log.i(DEBUG_TAG, msg);
    }
    
    public static void d(String tag,String msg) {
    	if(DEBUG_TRACE)
    		Log.d(tag, msg);
    }
    
    public static void e(String tag,String msg) {
        if(DEBUG_TRACE)
        	Log.e(tag, msg);
    }
}
