/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.lxm.pwhelp.utils;

import android.util.Log;

public class LogUtil {
    private static final String DEBUG_TAG = "pwhelper";
    private static final boolean DEBUG_TRACE = true;
    
    public static void i(String msg) {
        Log.i("pwhelper", msg);
    }
    
    public static void d(String msg) {
        Log.d("pwhelper", msg);
    }
    
    public static void e(String msg) {
        Log.e("pwhelper", msg);
    }
}
