/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.lxm.pwhelp.bean;


public class PWItem {
    private String created;
    private boolean deleted;
    private int item_id;
    private String item_name;
    private String item_type;
    private String modified;
    private String password;
    private String question1;
    private String question2;
    private String username;
    
    public PWItem() {
    }
    
    public String toString() {
    	StringBuilder sb = new StringBuilder();
        sb.append(item_id + ";");
        sb.append(item_name + ";");
        sb.append(item_type + ";");
        sb.append(username + ";");
        sb.append(password + ";");
        return sb.toString();
    }
    
    public int getItem_id() {
        return item_id;
    }
    
    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }
    
    public String getItem_name() {
        return item_name;
    }
    
    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }
    
    public String getItem_type() {
        return item_type;
    }
    
    public void setItem_type(String item_type) {
        this.item_type = item_type;
    }
    
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getQuestion1() {
        return question1;
    }
    
    public void setQuestion1(String question1) {
        this.question1 = question1;
    }
    
    public String getQuestion2() {
        return question2;
    }
    
    public void setQuestion2(String question2) {
        this.question2 = question2;
    }
    
    public String getCreated() {
        return created;
    }
    
    public void setCreated(String created) {
        this.created = created;
    }
    
    public String getModified() {
        return modified;
    }
    
    public void setModified(String modified) {
        this.modified = modified;
    }
    
    public boolean isDeleted() {
        return deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
